name: Deploy Built Extension

on:
  push:
    branches:
      - main  # Or any branch you use for releases
      - master

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '21.7.1'
      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build  # Make sure this scripts builds your React app

      - name: Zip the build folder
        run: cd dist && zip -r ../build.zip * && cd ../

      - name: Upload the build
        env:
          CHUB_AUTH_TOKEN: ${{ secrets.CHUB_AUTH_TOKEN }}
        run: |      # Replace the extension/<id>/upload with your extension's ID.
          curl -H "CH-API-KEY: ${{ secrets.CHUB_AUTH_TOKEN }}" -F "file=@build.zip" https://api.chub.ai/extension/${{ secrets.EXTENSION_ID }}/upload
